services:
  tango-db:
    environment:
     - MYSQL_ROOT_PASSWORD=root
    build:
      context: micromax/tango-db
  tango-cs:
    image: registry.gitlab.com/tango-controls/docker/tango-cs:9.3.5
    ports:
     - "10000:10000"
    environment:
     - TANGO_HOST=localhost:10000
     - MYSQL_HOST=tango-db:3306
     - MYSQL_USER=tango
     - MYSQL_PASSWORD=tango
     - MYSQL_DATABASE=tango
    depends_on:
     - tango-db
  csproxy-tango-db:
    image: registry.gitlab.com/tango-controls/docker/mysql:5
    environment:
     - MYSQL_ROOT_PASSWORD=root
  g-v-csproxy-0:
    image: registry.gitlab.com/tango-controls/docker/tango-cs:9.3.5
    environment:
     - ORB_PORT=10312
     - TANGO_HOST=localhost:10312
     - MYSQL_HOST=csproxy-tango-db:3306
     - MYSQL_USER=tango
     - MYSQL_PASSWORD=tango
     - MYSQL_DATABASE=tango
    depends_on:
     - csproxy-tango-db
  # runs 'g-v-csproxy-0' tango device servers
  csproxy-ds:
    environment:
     - TANGO_HOST=g-v-csproxy-0:10312
    build:
      context: common/csproxy-ds
  micromax-ds:
    environment:
     - TANGO_HOST=tango-cs:10000
    build:
      context: micromax/device-servers
    depends_on:
     - tango-cs
  mxcube:
    ports:
     - "5000:5000"  # Dashboard
     - "5173:5173"  # Vite development server
     - "8081:8081"  # MXCuBE
     - "8082:8082"  # Video Streamer
    environment:
     - TANGO_HOST=tango-cs:10000
    build:
      context: micromax/mxcube
  b-micromax-md3-pc:
    build:
      context: micromax/b-micromax-md3-pc
  b-micromax-isara-0:
    build:
      context: micromax/b-micromax-isara-0
  pandabox:
    build:
      context: micromax/pandabox
  dbg:
    environment:
     - TANGO_HOST=tango-cs:10000
    build:
      context: micromax/dbg
