# Redis server
[watcher:redis]
cmd = /opt/conda/bin/redis-server
working_dir = /tmp

# MXCuBE
[watcher:mxcube]
cmd = /app/web/mxcubeweb-server --repository /app/conf/MicroMAX --static-folder /opt/mxcube/build
copy_env = True
working_dir = /app
hooks.before_start = tango_ping.wait_for_tango

[env:mxcube]
PYTHONPATH = $PYTHONPATH:/opt/circus/

# Dashboard
[watcher:dashboard]
cmd = /opt/conda/bin/flask --app server run --host 0.0.0.0
working_dir = /app/dboard
