MXCUBE_CONFIG_DIR="/app/conf"
MXCUBE_START_COMMAND="/opt/conda/bin/circusctl start mxcube"
MXCUBE_STOP_COMMAND="/opt/conda/bin/circusctl stop mxcube"
VIDEO_STREAM_PROTOCOL="ws"
MXCUBE_HOST="localhost:8082"
